### ISSUE TITLE
Failed to connect to Polar H10

### ISSUE THREAD

**Issue by BunnyMerz** [luisqtr/exciteometer-devices-UWP#1]
I have attempted to use both the UWP and the Android builds to connect to a Polar H10, but have failed in both instances.

For the Windows attempt, the computer does not find the Polar through its native Bluetooth, but it manages to enumerate it through the app. Attempting to pair results in a fail after about 3 seconds. I even attempted running it on Linux using Wine, since the Linux machine managed to pair with the Polar natively, but failed to even run the app due to missing DLL's sadly.

Tho this isn't the Android repository, I will also list my attempts at it. For the Android, the phone finds the equipment, pairs with it, but the app doesn't show any incoming data (after inputting the correct ID). I have tried using two different phones, both failed in the same way.

I'm out of options! Any help?

**Comment by luisqtr** [comment]
Hi.

Check your Windows device, it should find the PolarH10 through Bluetooth without problem [see img below].

Then, you can connect via the Excite-O-Meter Windows app.

Unforunately I haven't tried the Android solution in a long time, so I can't tell if it's still working.

![image](https://github.com/user-attachments/assets/08d36c66-bd3b-426f-9d72-044a138dc315)

**Comment by BunnyMerz** [comment]
Sorry for creating an unnecessary issue! I attempted to use the app in a Windows 11 which is most likely why it failed (sadly, there were no Win10 available to me at the time). A colleague tried with Win10 and it worked perfectly! Although the problem with the android version still exists.

**Comment by BunnyMerz** [comment]
I found a solution to my problem! It seems that Windows 11 by default comes with an option to hide devices that are not "Low-Energy" (tho I thought the Polar was considered one). Here is the reference for the solution: [Reddit Post: Windows 11 Bluetooth issues FIXED!](https://www.reddit.com/r/cricut/comments/14h9sz8/windows_11_bluetooth_issues_fixed/)

Go to `Bluetooth & devices > Devices` and there will be an option for `Bluetooth devices discovery` that should be set to `Advanced` and not `Default`. Now the Polar should appear in the Bluetooth discovery list.

If connecting is still an issue, go to `Printers and other devices` (the old Windows 7 place you'd connect Bluetooth devices) and connect trough there. It will attempt to install the necessary drivers and work!
